---
- hosts: all
  become: true
  tasks:

    - name: Ensure apache is latest
      ansible.builtin.apt:
          name: apache2
          state: latest

    - name: Write apache config file
      ansible.builtin.template:
        src: /etc/apache2/apache2.conf
        dest: /etc/apache2/apache2.conf

    - name: Ensure postgresql is at the latest version
      ansible.builtin.apt:
        name: postgresql
        state: latest

    - name: Ensure that postgresql is started
      ansible.builtin.service:
        name: postgresql
        state: started
